version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./MySQL:/var/lib/mysql
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=12345612
          - MYSQL_DATABASE=ingweb
        ports:
          - "3306:3306"
  apache-php:
    container_name: apache-php
    build:
      context: ./
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql